In [15]:
import pandas as pd

In [16]:
df = pd.read_csv("Gen_Z_Emotion_Level_Dataset.csv")

In [17]:
drop_column = ['Insight','saran','Saran']
df.drop(drop_column, axis=1, inplace=True)
df.to_csv('emotion_dataset.csv', index=False)

In [18]:
new_df = pd.read_csv("emotion_dataset.csv")
new_df.sample(10)

     anxiety  fear  nervousness  sadness  suffering  shame
421        0     2            0        0          3      2
248        1     0            0        0          2      3
360        0     2            0        1          1      0
467        0     0            1        3          0      3
13         2     2            2        0          0      0
336        0     2            2        0          0      1
507        0     0            3        0          2      1
499        0     0            2        0          2      2
393        0     2            0        3          0      1
32         1     2            0        3          0      0

In [19]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 540 entries, 0 to 539
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   anxiety      540 non-null    int64
 1   fear         540 non-null    int64
 2   nervousness  540 non-null    int64
 3   sadness      540 non-null    int64
 4   suffering    540 non-null    int64
 5   shame        540 non-null    int64
dtypes: int64(6)
memory usage: 25.4 KB

In [ ]:
def get_emotion_insight(row):
    emotions = ['cemas', 'rasa takut', 'gelisah', 'kesedihan', 'penderitaan', 'rasa malu']
    levels = {0: 'tidak ada', 1: 'sedikit', 2: 'lumayan', 3: 'tinggi'}
    
    insight = []
    for idx, value in enumerate(row):
        if value > 0:
            emotion = emotions[idx]
            level = levels[value]
            insight.append(f"{emotion} {level}")
    
    return ', '.join(insight)

# Menerapkan fungsi untuk setiap baris
new_df['insight'] = new_df.apply(get_emotion_insight, axis=1)

new_df.to_csv('emotion_insight_dataset.csv', index=False)

In [22]:
df_insight = pd.read_csv("emotion_insight_dataset.csv")
df_insight.head()

,anxiety,fear,nervousness,sadness,suffering,shame,insight
0,1,1,1,0,0,0,"cemas sedikit, rasa takut sedikit, gelisah sed..."
1,1,1,2,0,0,0,"cemas sedikit, rasa takut sedikit, gelisah lum..."
2,1,1,3,0,0,0,"cemas sedikit, rasa takut sedikit, gelisah tinggi"
3,1,2,1,0,0,0,"cemas sedikit, rasa takut lumayan, gelisah sed..."
4,1,2,2,0,0,0,"cemas sedikit, rasa takut lumayan, gelisah lum..."